Ral/wi00681235/pointer based behaviors should support pan changed new
WiseTechGlobal/Blazor.Diagrams pull request #15
Opened 2023-12-18 03:15 UTC by Alvarenga1

2023-12-18 06:21 UTC, Heathermcx commented
Can we also add tests for the changes to resizer providers

2023-12-18 06:22 UTC, Heathermcx requested changes

2023-12-18 06:22 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Behaviors/DragNewLinkBehavior.cs
> +        OngoingLink!.RefreshLinks();
not important but you don't need the `!` again.

2023-12-18 06:22 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Behaviors/DragNewLinkBehavior.cs
> +    private void OnPointerMove(WheelEventArgs e)
`OnWheel` ?

2023-12-18 06:22 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Behaviors/DragMovablesBehavior.cs
> +    public void OnPointerMove(WheelEventArgs e)
`OnWheel`?

2023-12-18 06:22 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Behaviors/DragMovablesBehavior.cs
> +        _moved = true;
Should this be in `MoveNodes` as well?

2023-12-18 06:22 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Behaviors/DragMovablesBehavior.cs
> +    private void moveNodes(Model? model, double deltaX, double deltaY)
```suggestion
    private void MoveNodes(Model? model, double deltaX, double deltaY)
```

2023-12-18 22:46 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Positions/Resizing/IResizerProvider.cs
> +        public void OnPointerMove(WheelEventArgs args);
Fixed

2023-12-18 22:49 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Behaviors/DragNewLinkBehavior.cs
> +        OngoingLink!.RefreshLinks();
Fixed

2023-12-18 22:49 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Behaviors/DragNewLinkBehavior.cs
> +    private void OnPointerMove(WheelEventArgs e)
Fixed

2023-12-18 22:49 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Behaviors/DragMovablesBehavior.cs
> +    public void OnPointerMove(WheelEventArgs e)
Fixed

2023-12-18 22:54 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Behaviors/DragMovablesBehavior.cs
> +    private void moveNodes(Model? model, double deltaX, double deltaY)
Fixed

2023-12-18 22:56 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Behaviors/DragMovablesBehavior.cs
> +        _moved = true;
We can keep this here

2023-12-18 22:57 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Positions/Resizing/BottomLeftResizerProvider.cs
> +            if (_nodeModel is null || _lastClientX == null || _lastClientY == null)
Fixed

2023-12-19 00:46 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Positions/Resizing/BottomLeftResizerProvider.cs
> +            }
Fixed

2023-12-19 21:28 UTC, Heathermcx approved these changes

2023-12-20 23:56 UTC, matatouille commented on src/Blazor.Diagrams.Core/Behaviors/DragMovablesBehavior.cs
> +        if (_initialPositions.Count == 0 || _lastClientX == null || _lastClientY == null)
We have made it so that the wheel behaviors are configurable
https://github.com/WiseTechGlobal/Blazor.Diagrams/blob/8561ff2f39d31615cd90970daab868e77792ed85/src/Blazor.Diagrams.Core/Options/DiagramBehaviorOptions.cs#L10C9-L16C70

I think we should only be moving the node on wheel event if the wheel event will result in a scroll. By default in Blazor Diagrams, the wheel event will zoom the diagram so this isn't needing in those cases. I think we should be doing a check here (and in the other files) that the diagram is setup to handle this wheel event as a pan behavior

2024-01-08 00:47 UTC, matatouille requested changes

2024-01-08 00:47 UTC, matatouille commented on src/Blazor.Diagrams.Core/Behaviors/ScrollBehavior.cs
> +            Diagram.SetPan(x, y, deltaX, deltaY, _lastClientX, _lastClientY);
this feels wrong - we shouldn't need to work out the client X/Y position to initiate a pan
pan can be invoked by non pointer based events (such as this) - I think the better solution is to refactor DragNewLinkBehavior to not require the client x/y position to move, similar to how the DragMoveables behavior works

2024-01-08 00:47 UTC, matatouille commented on src/Blazor.Diagrams.Core/Diagram.cs
> +    public void SetPan(double x, double y, double deltaX = 0, double deltaY = 0, double clientX = 0, double clientY = 0)
rather than needing to explicitly pass in the delta here, we should probably calculate it by using the current pan value and the new pan value

2024-01-09 03:32 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Behaviors/ScrollBehavior.cs
> +            Diagram.SetPan(x, y, deltaX, deltaY, _lastClientX, _lastClientY);
Fixed

2024-01-09 03:32 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Diagram.cs
> +    public void SetPan(double x, double y, double deltaX = 0, double deltaY = 0, double clientX = 0, double clientY = 0)
Fixed

2024-01-10 04:01 UTC, matatouille commented on src/Blazor.Diagrams.Core/Behaviors/DragNewLinkBehavior.cs
> +        UpdateLinkPosition((double)_lastClientX!, (double)_lastClientY!);
imo using a `!` in production code to supress nullable issues is not good
Should we just add null checks above like we do in OnPointerMove?
eg. `|| _lastClientX == null || _lastClientY == null`

2024-01-10 04:02 UTC, matatouille commented on src/Blazor.Diagrams.Core/Behaviors/DragNewLinkBehavior.cs
> +            if (nearPort != null || OngoingLink!.Target is not PositionAnchor)
same here - can we just check if OutgoingLink is null at the beginning and return?

2024-01-10 04:02 UTC, matatouille commented on src/Blazor.Diagrams.Core/Behaviors/PanBehavior.cs
> +﻿using Blazor.Diagrams.Core.Behaviors.Base;
are these needed?

2024-01-10 04:04 UTC, matatouille commented on src/Blazor.Diagrams.Core/Diagram.cs
> +        PanChanged?.Invoke(x, y);
this will be calling PanChanged with the new X and Y, not the delta which the code is expecting.
I think you will need to capture the old Pan and do `oldPan.X - Pan.X`

2024-01-15 05:40 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Diagram.cs
> +        PanChanged?.Invoke(x, y);
fixed

2024-01-15 05:40 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Behaviors/PanBehavior.cs
> +﻿using Blazor.Diagrams.Core.Behaviors.Base;
yes, thsore are all required. the only change was in what order they appear

2024-01-15 05:41 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Behaviors/DragNewLinkBehavior.cs
> +            if (nearPort != null || OngoingLink!.Target is not PositionAnchor)
fixed

2024-01-15 05:41 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Behaviors/DragNewLinkBehavior.cs
> +        UpdateLinkPosition((double)_lastClientX!, (double)_lastClientY!);
fixed

2024-01-18 02:22 UTC, matatouille approved these changes

2024-01-18 23:50 UTC, Heathermcx requested changes
Hi Renan, looks pretty good. Just added a few comments to address - mostly about adding and updating documentation. 
Also resolve merge conflicts - let me know if you would like help with this - I think it will be mostly from changes I merged recently

2024-01-18 23:50 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Positions/Resizing/ResizerProvider.cs
> +        abstract public bool ShouldAddTotalMovedY { get; }
Let's consider how we can document this to make it easier for someone to create their own implementation. e.g. we could add a documentation page similar to [the position provider page](https://blazor-diagrams.zhaytam.com/documentation/position-providers) and/or perhaps documentation comments would be useful here

2024-01-18 23:50 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Positions/Resizing/ResizerProvider.cs
> +        private NodeModel _nodeModel = null!;
lets make these all nullable rather than using `null!`

2024-01-18 23:50 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Positions/Resizing/ResizerProvider.cs
> +        private NodeModel _nodeModel = null!;
see changes made here: https://github.com/WiseTechGlobal/Blazor.Diagrams/pull/16/files/22f4c2ad54fc7df42e10b54111f9ece4a3b5c55d..a0f35806ba7ba4fb8fd2481d98690e884d31cbf2

2024-01-18 23:50 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Controls/Default/ResizeControl.cs
> +        public ResizeControl(ResizerProvider resizeProvider)
Update documentation to match changes. On [this page](https://github.com/WiseTechGlobal/Blazor.Diagrams/blob/b76d767756d21c808852f6ff3abcd1d0bf512ef5/site/Site/Pages/Documentation/Controls/Overview.razor#L143C103-L143C155), `IResizerProvider` will need to be changed to `ResizerProvider`

2024-01-18 23:50 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Diagram.cs
> +    public event Action<double, double>? PanChanged;
Update the `PanChanged` type on the [Diagram API page](https://blazor-diagrams.zhaytam.com/documentation/diagram-api)

2024-01-22 23:48 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Positions/Resizing/ResizerProvider.cs
> +        private NodeModel _nodeModel = null!;
Fixed

2024-01-22 23:58 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Controls/Default/ResizeControl.cs
> +        public ResizeControl(ResizerProvider resizeProvider)
Fixed

2024-01-23 00:01 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Diagram.cs
> +    public event Action<double, double>? PanChanged;
Fixed

2024-01-23 01:34 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Positions/Resizing/ResizerProvider.cs
> +        }
do we need to implement this method here? I think we should require that the child class implements it instead - I think it will be less confusing that way

2024-01-23 03:08 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Positions/Resizing/ResizerProvider.cs
> +        }
fixed

2024-01-23 03:08 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Positions/Resizing/ResizerProvider.cs
> +        abstract public bool ShouldAddTotalMovedY { get; }
fixed

2024-01-23 22:41 UTC, Heathermcx approved these changes

2024-01-24 01:00 UTC, matatouille approved these changes

2024-02-13 03:57 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Positions/Resizing/ResizerProvider.cs
> +        ///<summary> Controls whether the width should be modified on Node resizing </summary>
Is this comment correct? I think `ShouldAddTotalMovedX` determines if the total moved should be added or subtracted, not if the width should be modified or not

2024-02-18 22:24 UTC, matatouille approved these changes

2024-02-19 00:47 UTC, Heathermcx requested changes
I think that the design regarding updating port positions on resize should be reconsidered. 
The problem you are trying to solve with the port position changes actually exist in master and are not directly related to the work you are doing here with pointer based behaviors. I think it makes more sense for us to chunk this into a new WI/PR.

2024-02-19 00:47 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Models/NodeModel.cs
> +    private void UpdatePortPositions(double oldWidth, double oldHeight, double newWidth, double newHeight)
could the two `UpdatePortPositions` be renamed to differentiate them and/or documentation comments added?

2024-02-19 00:47 UTC, Heathermcx commented on tests/Blazor.Diagrams.Core.Tests/Positions/Ports/PortTests.cs
> +        public void UpdatePortOnSetPosition(PortAlignment alignment)
do these tests belong here or are they tests for the `NodeModel`? the logic that you are testing is in `NodeModel`. Perhaps this is a red flag that the `UpdatePortPosition` methods should actually be in `PortModel` and then these tests are `PortModelTests`.

2024-02-19 00:47 UTC, Heathermcx commented on tests/Blazor.Diagrams.Core.Tests/Positions/Ports/PortTests.cs
> +            var expected = new Point(port.Position.X + deltaX, port.Position.Y + deltaY);
I think expected value should be hard coded in the test case data

2024-02-19 00:47 UTC, Heathermcx commented on tests/Blazor.Diagrams.Core.Tests/Positions/Ports/PortTests.cs
> +            Point expected = alignment switch
I think that the expected values should be hard coded in test case data.

2024-02-19 22:27 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Models/NodeModel.cs
> +    private void UpdatePortPositions(double oldWidth, double oldHeight, double newWidth, double newHeight)
fixed

2024-02-19 23:51 UTC, Heathermcx approved these changes

2024-02-20 00:29 UTC, merged