An9/wi00692027/ncn buffer node relationship implementation
WiseTechGlobal/Blazor.Diagrams pull request #19
Opened 2024-01-15 19:06 UTC by AarthiNarayanan

Introduced Enabled property to handle the dragNewLinkBehaviour

2024-01-16 04:52 UTC, suraj-desai-wtg commented on src/Blazor.Diagrams.Core/Behaviors/DragNewLinkBehavior.cs
> +            if (port.Locked || port.Enabled)
Shouldn't it be !port.Enabled?

2024-01-16 06:03 UTC, AarthiNarayanan commented on src/Blazor.Diagrams.Core/Behaviors/DragNewLinkBehavior.cs
> +            if (port.Locked || port.Enabled)
Yes, when I changed the name I forgot change the implementation as per the name, I have changed it now.

2024-01-17 06:05 UTC, suraj-desai-wtg commented on tests/Blazor.Diagrams.Core.Tests/Behaviors/DragNewLinkBehaviorTests.cs
> +            Size = new Size(10, 20),
Minor: We don't need this change anymore after changing to !Enabled

2024-01-17 06:06 UTC, suraj-desai-wtg requested changes
PR is ready to merge after addressing a minor comment that I left

2024-01-17 13:06 UTC, AarthiNarayanan commented on tests/Blazor.Diagrams.Core.Tests/Behaviors/DragNewLinkBehaviorTests.cs
> +            Size = new Size(10, 20),
Removed comma

2024-01-17 13:11 UTC, merged