WI00713829 - Ports dont update when resizing nodes in Blazor Diagrams
WiseTechGlobal/Blazor.Diagrams pull request #26
Opened 2024-02-21 22:46 UTC by Alvarenga1

Fixed an issue causing port position to not be calculated during resizing of nodes.

2024-02-21 23:49 UTC, Heathermcx requested changes

2024-02-21 23:49 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Models/NodeModel.cs
> +            port.RefreshLinks();
Does this logic belong in the PortModel?

2024-02-21 23:49 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Models/NodeModel.cs
> +    /// Updates the position of the ports by calculating the difference between the old and new size when the node is resized
```suggestion
    /// Updates port positions when node size changes.
```

2024-02-21 23:49 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Models/NodeModel.cs
> +    private void UpdatePortPositions(double oldWidth, double oldHeight, double newWidth, double newHeight)
maybe just pass in `Size oldSize` and `Size newSize`? I think that would be easier to read

2024-02-21 23:49 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Models/NodeModel.cs
> +    /// Updates port position based on the deltaX and deltaY when the node is moved
```suggestion
    /// Updates port positions when node position changes.
```

2024-02-22 01:22 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Models/NodeModel.cs
> +    /// Updates the position of the ports by calculating the difference between the old and new size when the node is resized
Fixed

2024-02-22 01:23 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Models/NodeModel.cs
> +    private void UpdatePortPositions(double oldWidth, double oldHeight, double newWidth, double newHeight)
Fixed

2024-02-22 01:24 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Models/NodeModel.cs
> +    /// Updates port position based on the deltaX and deltaY when the node is moved
Fixed

2024-02-22 02:39 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Models/NodeModel.cs
> +            port.RefreshLinks();
Fixed

2024-02-22 04:04 UTC, Heathermcx requested changes

2024-02-22 04:22 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Models/NodeModel.cs
> +        var deltaY = newSize.Height - oldSize.Height;
I don't think so, they are used in the same way in both contexts, which is how much we need to offset the current port position by.

2024-02-22 22:55 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Models/PortModel.cs
> +    public void calculateNewPortPosition(double deltaX, double deltaY)
Fixed

2024-02-22 22:58 UTC, Alvarenga1 commented on tests/Blazor.Diagrams.Core.Tests/Models/NodeModelTest.cs
> +            Assert.Equal(300, port.Position.Y);
No, we're using the deltaX and deltaY to calculate the resulting port position by adding those values tothe current port position, this calculation is done in the UpdatePortPositions method in NodeModel.cs

2024-02-22 23:38 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Models/PortModel.cs
> +    public void calculateNewPortPosition(double deltaX, double deltaY)
fixed

2024-02-28 03:36 UTC, Heathermcx requested changes

2024-02-28 03:36 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Models/NodeModel.cs
> +        if (newSize.Equals(_size) == true || Size == null)
I don't think we should return early if Size is null. We should still set the size. 
Maybe what you're looking for is something like 
```
if (Size != null) 
{
   UpdatePortPositions(Size, newSize);
}
Size = newSize;
```

2024-02-28 03:36 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Models/NodeModel.cs
> +        var deltaY = newSize.Height - oldSize.Height;
I don't agree. They are used quite differently. If they were the same, we wouldn't need two `UpdatePortPositions` methods. In general we are refering to the position coordinates by `X` and `Y` and dimensions by `width` and `height` so I'm not sure why when we are talking about a change in position or dimensions we suddenly start using the same words to refer to different things.
Doesn't need to be `deltaHeight` and `deltaWidth` but I do think it should be different to `deltaX` and `deltaY` to improve the readability of the two methods.

2024-02-28 03:36 UTC, Heathermcx commented on tests/Blazor.Diagrams.Core.Tests/Blazor.Diagrams.Core.Tests.csproj
Do we need these changes?

2024-02-28 03:36 UTC, Heathermcx commented on tests/Blazor.Diagrams.Core.Tests/Models/NodeModelTest.cs
> +
```suggestion

```

2024-02-28 03:36 UTC, Heathermcx commented on tests/Blazor.Diagrams.Core.Tests/Models/PortModelTest.cs
> +                    break;
I think that the expected values should be part of the `InlineData`, not as logic in the test.

2024-02-28 03:41 UTC, Heathermcx commented on tests/Blazor.Diagrams.Core.Tests/Models/NodeModelTest.cs
> +            Assert.Equal(300, port.Position.Y);
As discussed, the port position was not being initialized as expected which is why all of the ports were in the top left corner of the node after the position change. We have updated the test to initialize the port position and check that the post position is correctly set after the position change.

2024-02-28 04:56 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Models/NodeModel.cs
> +        var deltaY = newSize.Height - oldSize.Height;
Fixed

2024-02-28 05:29 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Models/NodeModel.cs
> +        if (newSize.Equals(_size) == true || Size == null)
I don't think it makes sense to move the port before the node is resized, what do you think of this alternative approach ?
 ```csharp
public void SetSize(double width, double height)
    {
        var newSize = new Size(width, height);
        if (newSize.Equals(_size) == true)
            return;

        Size? oldSize = Size != null ? new Size(Size.Width, Size.Height) : null;

        Size = newSize;
        if (oldSize != null)
        {
            UpdatePortPositions(oldSize, newSize);
        }
        Refresh();
        RefreshLinks();
        SizeChanging?.Invoke(this);
    }
```

2024-02-28 05:33 UTC, Alvarenga1 commented on tests/Blazor.Diagrams.Core.Tests/Blazor.Diagrams.Core.Tests.csproj
Reverted

2024-02-28 05:33 UTC, Alvarenga1 commented on tests/Blazor.Diagrams.Core.Tests/Models/NodeModelTest.cs
> +
fixed

2024-02-28 05:40 UTC, Alvarenga1 commented on tests/Blazor.Diagrams.Core.Tests/Models/PortModelTest.cs
> +                    break;
fixed

2024-02-28 23:22 UTC, Heathermcx reviewed
Hi Renan, just a couple more minor changes from feedback not entirely addressed in previous review.

2024-02-28 23:22 UTC, Heathermcx commented on tests/Blazor.Diagrams.Core.Tests/Models/PortModelTest.cs
> +            }
we don't need this switch if in every case we are doing the same thing .

2024-02-28 23:22 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Models/PortModel.cs
> +    public virtual void SetPortPositionOnNodeSizeChanged(double deltaX, double deltaY)
`deltaWidth`, `deltaHeight` for consistency

2024-02-28 23:47 UTC, Alvarenga1 commented on tests/Blazor.Diagrams.Core.Tests/Models/PortModelTest.cs
> +            }
fixed

2024-02-29 01:06 UTC, Heathermcx approved these changes

2024-02-29 01:49 UTC, merged