WI00737678---RemoveDragNodesBehavior
WiseTechGlobal/Blazor.Diagrams pull request #39
Opened 2024-06-04 15:56 UTC by gnawisetech

WI00737678---RemoveDragNodesBehavior

2024-06-07 12:31 UTC, tripti-wani approved these changes

2024-06-07 21:07 UTC, toluwtglobal approved these changes

2024-06-12 00:15 UTC, tripti-wani approved these changes

2024-06-12 02:07 UTC, Heathermcx requested changes

2024-06-12 02:07 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Behaviors/DragMovablesBehavior.cs
Blazor.Diagrams does not have a concept of child shapes. The most similar feature in Blazor.Diagrams is groups but we do not use groups to implement child nodes in NCN. 
In my opinion, we should not add any code or logic about child shapes to Blazor.Diagrams. Instead, this work item should focus on making `DragMovablesBehavior` customizable so that we can inject our own specialized behavior for child nodes from our own NCN project. Some ideas to achieve this is to add some events to hook into or make some of the methods virtual so we can override them in our own project. There should not be a lot of code change (and no functionality change) in Blazor.Diagrams for this work item, most of the changes will be in our NCN project.
Let's talk about this later today.

2024-06-12 07:30 UTC, gnawisetech commented
Abandoning the pr.

2024-06-13 04:56 UTC, closed without merging