SelectionBox now updates when scrolling
WiseTechGlobal/Blazor.Diagrams pull request #40
Opened 2024-06-12 05:28 UTC by Alvarenga1

2024-06-12 08:36 UTC, gnawisetech commented on src/Blazor.Diagrams.Core/Behaviors/SelectionBoxBehavior.cs
> +            if (_initialClientPoint == null || _lastClientX == null || _lastClientY == null)
Did you mean - deltaX, deltaY instead of _lastClientX and _lastClientY.

2024-06-12 23:55 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Behaviors/SelectionBoxBehavior.cs
> +            if (_initialClientPoint == null || _lastClientX == null || _lastClientY == null)
No, this is correct. We're not using the deltaX and deltaY for this since we're adding the Pan when updating.

2024-06-13 03:13 UTC, gnawisetech approved these changes

2024-06-13 17:20 UTC, toluwtglobal approved these changes

2024-06-14 00:32 UTC, Heathermcx requested changes
Hi Renan, the select box moves well on scroll, nice work. However, it does not select the nodes within the box unless the mouse moves. 
I think that OnPanChanged is missing the logic for selecting the nodes that is at the end of OnPointerMove. I suggest to try move that logic to a new method so we can reuse it in OnPanChanged.

2024-06-14 00:32 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Behaviors/SelectionBoxBehavior.cs
> +            var start = Diagram.GetRelativePoint(_initialClientPoint!.X + Diagram.Pan.X - _initialPan.X, _initialClientPoint.Y + Diagram.Pan.Y - _initialPan.Y);
Let's make sure we aren't accessing nullable attributes without doing a null check. We can return early if at the start of this method _initialPan is null.

2024-06-17 04:23 UTC, Alvarenga1 commented on src/Blazor.Diagrams.Core/Behaviors/SelectionBoxBehavior.cs
> +            var start = Diagram.GetRelativePoint(_initialClientPoint!.X + Diagram.Pan.X - _initialPan.X, _initialClientPoint.Y + Diagram.Pan.Y - _initialPan.Y);
Fixed

2024-06-19 02:52 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Behaviors/SelectionBoxBehavior.cs
> +        public void OnPanChanged(double deltaX, double deltaY)
TODO: let's also add a test with these changes. We should be testing that the nodes are selected on pan changed. Similar to `Behavior_WithBoundsChangedDelegate_ShouldSelectNodesInsideArea()`

2024-06-19 02:53 UTC, Heathermcx requested changes
Functionality works well. Make sure to add tests for the latest change.

2024-06-19 22:51 UTC, Heathermcx approved these changes
Looks good

2024-06-20 03:40 UTC, merged