WI00737678---RemoveDragNodesBehavior
WiseTechGlobal/Blazor.Diagrams pull request #43
Opened 2024-07-02 07:51 UTC by gnawisetech

WI00737678---RemoveDragNodesBehaviorUpdates

2024-07-03 01:44 UTC, Heathermcx requested changes

2024-07-03 01:44 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Behaviors/DragMovablesBehavior.cs
> +    protected readonly Dictionary<NodeModel, NodeMoveablePositions> _initialPositions;
I think we have some misunderstanding from yesterday. We should not add `ChildPositions` in Blazor.Diagrams, I thought we will just make `_initialPositions` protected so that we can reuse it in our implementation. Is there a solution where we use `_initialPositions` from this base class in our implementation? 
```suggestion
       protected readonly Dictionary<MovableModle, Point> _initialPositions;
```

2024-07-04 07:21 UTC, gnawisetech commented on src/Blazor.Diagrams.Core/Behaviors/DragMovablesBehavior.cs
> +    protected readonly Dictionary<NodeModel, NodeMoveablePositions> _initialPositions;
Updated

2024-07-05 08:39 UTC, Heathermcx commented on src/Blazor.Diagrams.Core/Behaviors/DragMovablesBehavior.cs
> +        ResetPan();
We can't add this to Blazor.Diagrams - this means that every time I try to drag a node, the diagram view is repositioned to 0,0 even if I have panned the diagram. This makes it really hard to drag the node and also changes the users view without them trying to change view.

2024-07-10 00:01 UTC, Heathermcx approved these changes

2024-07-10 02:22 UTC, tripti-wani approved these changes

2024-07-11 05:14 UTC, merged