WI00761833 - Updates for Blazor Diagrams mouse configuration
WiseTechGlobal/Blazor.Diagrams pull request #45
Opened 2024-07-09 05:38 UTC by shams-azam-wtg

- Added documentation for scroll behavior
- Fixed scrolling of page with diagram when scrolling insied a diagrm by adding a js function in script.js to implement preventDefault.
- updated minimized js of script.js to script.min.js as just adding to script.js was not working when tested locally.

2024-07-09 23:34 UTC, Heathermcx requested changes

2024-07-09 23:34 UTC, Heathermcx commented on src/Blazor.Diagrams/Components/DiagramCanvas.razor.cs
> +            await JSRuntime.AddDefaultPreventingHandler(elementReference);
I think that we should only prevent scroll for diagrams that have scroll on wheel.

2024-07-09 23:34 UTC, Heathermcx commented on src/Blazor.Diagrams/Extensions/JSRuntimeExtensions.cs
> +    public static async Task AddDefaultPreventingHandler(this IJSRuntime jsRuntime, ElementReference element)
seeing as this method is specific to preventing default for wheel, let's name it to indicate that

2024-07-09 23:34 UTC, Heathermcx commented on site/Site/Pages/Documentation/Diagram/Behaviors.razor
> +Diagram.RegisterBehavior(new ScrollBehavior(Diagram));
This does not enable scroll on wheel behavior. 
We need to use the diagram `BehaviorOptions` to configure what action scrolls the diagram. I think `BehaviorOptions` is what we need to document here.
e.g. to scroll on wheel for a diagram, use `_diagram.BehaviorOptions.DiagramWheelBehavior = _diagram.GetBehavior<ScrollBehavior>();`

2024-07-09 23:34 UTC, Heathermcx commented on src/Blazor.Diagrams/Components/DiagramCanvas.razor.cs
> +    private async void OnWheel(WheelEventArgs e)
does this method need to be async?

2024-07-10 04:02 UTC, shams-azam-wtg commented on src/Blazor.Diagrams/Extensions/JSRuntimeExtensions.cs
> +    public static async Task AddDefaultPreventingHandler(this IJSRuntime jsRuntime, ElementReference element)
changed to AddDefaultPreventingForWheelHandler

2024-07-10 04:03 UTC, shams-azam-wtg commented on src/Blazor.Diagrams/Components/DiagramCanvas.razor.cs
> +    private async void OnWheel(WheelEventArgs e)
removed async.

2024-07-10 05:03 UTC, shams-azam-wtg commented on src/Blazor.Diagrams/Components/DiagramCanvas.razor.cs
> +            await JSRuntime.AddDefaultPreventingHandler(elementReference);
modified to prevent scroll only for Scroll Behavior on wheel.

2024-07-10 05:04 UTC, shams-azam-wtg commented on site/Site/Pages/Documentation/Diagram/Behaviors.razor
> +Diagram.RegisterBehavior(new ScrollBehavior(Diagram));
updated.

2024-07-11 02:44 UTC, Heathermcx requested changes
Hi Shams, the functionality works well now, nice work. 
I think we can improve the documentation some more.

2024-07-11 02:44 UTC, Heathermcx commented on site/Site/Pages/Documentation/Diagram/Behaviors.razor
> +<h2>Using Different Behaviors</h2>
`Using Different Behaviors` seems like a duplicate of the above section, `Replacing a behavior`. I think what we really want to document here is how to configure behaviors use `DiagramBehaviorOptions` which is a class we added. This class allows the user to configure some of the standard behaviors to be on different inputs. This is different to `using a different behavior`/`replacing a behavior`.

2024-07-11 02:44 UTC, Heathermcx commented on site/Site/Pages/Documentation/Diagram/Behaviors.razor
> +<h2>Using Different Behaviors</h2>
Check with Matt if not sure how `DiagramBehaviorOptions` works.

2024-07-11 22:55 UTC, Heathermcx approved these changes
Looks good.

2024-07-15 03:34 UTC, archer0302 approved these changes

2024-07-15 03:35 UTC, merged